# SPDX-License-Identifier: GPL-2.0
# Single-file kbuild module (module and source share the dashed name luofu-wifi).
# Built by CI against vanilla 5.10.201 arm headers:
#   make -C <linux-5.10.201> M=$PWD ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules
# Lanes: .github/workflows/lab-module-build.yml (matrix.module), build-load-test-module.yml.
obj-m := luofu-wifi.o
